### ISSUE TITLE
Question about codebook

### ISSUE THREAD

**Issue by irmacastaneda0822** [cyouh95/recruiting-chapter#1]
Hi Crystal, 

For the private high school data (pss 2017-18), their codebook is a 100 page [word document](https://nces.ed.gov/surveys/pss/pssdata.asp). Is there a way to read in this file or can we only read in excel files? I was hoping to use the looping method you taught me to add variable labels to the data if possible. 

Thanks!
@cyouh95

**Comment by cyouh95** [comment]
It looks like there's also an [excel file](https://nces.ed.gov/surveys/pss/zip/layout2017_18.zip) under "File Layout" that contains the variable names and labels. I think you should be able to convert that to a CSV and read it in, but let me know if you run into any issues! @irmacastaneda0822

**Comment by ozanj** [comment]
can we close this issue?

**Comment by cyouh95** [comment]
Yup!
