### ISSUE TITLE
add figure(s) of number of events by type and in-state, out-of-state

### ISSUE THREAD

**Issue by ozanj** [cyouh95/recruiting-chapter#10]
Hey @cyouh95 !

Can you add figures for "number of events by type and in-state, out-of-state" to the recruiting chapter?

you can copy figure 2 from our most recent AERJ submission

Make separate figures for private colleges/universities and for public research universities [too many orgs to cram into a single figure].

totally fine to create these figures in python/javascript/d3 etc. whatever makes the task easiest for you.

in terms of placement, these will probably be the first figures in the results section.

Thank you!

**Comment by cyouh95** [comment]
Added to the `figures` folder! ([public](https://github.com/cyouh95/recruiting-chapter/blob/118bab33bb2accf79b632cf73a929cc89d55ed3e/assets/figures/plot_event_count_pub.pdf) & [private](https://github.com/cyouh95/recruiting-chapter/blob/118bab33bb2accf79b632cf73a929cc89d55ed3e/assets/figures/plot_event_count_priv.pdf))
