### ISSUE TITLE
Create map of Nashville schools for introduction

### ISSUE THREAD

**Issue by cyouh95** [cyouh95/recruiting-chapter#12]
- Nashville metro area
- Overlay by tract
  - Median household income
  - Population total
  - Race/ethnicity
- Icon for Vanderbilt University
- Pins for public & private HS (distinguish the 3 mentioned in intro)
  - Name of HS (maybe also date founded for the 3 schools)
  - Niche grade & rank (if A+ school)
  - Religious affiliation
  - Racial composition (% White, % Asian, % LatinX, % Black, % Other)
  - University visits 
    - Headings for private national, private libart, and public research
    - Include university name and visit date (can list univ multiple times if multiple visits)
    - Sort by visit date

**Comment by cyouh95** [comment]
- Map includes all of [Davidson County](https://en.wikipedia.org/wiki/Davidson_County,_Tennessee)
- 2017 ACS data for tracts
  - Median household income is for ages 25-64
  - Race/ethnicity is for ages 15-19
- Popups for HS
  - Some popups are very long bc of many visits by univs, so these are scrollable (can be adjusted)

**Comment by cyouh95** [comment]
- Include entire state of TN, just Zoom in to ~Davidson County~ Nashville-Davidson--Murfreesboro--Franklin, TN MSA
- Popups for HS
  - Add category AIAN/NHPI and mixed (~ignore Other group, won't add to 100%~ actually no Other group for HS data)
  - Increase font size / pop up size

**Comment by ozanj** [comment]
wonderful job on the map @cyouh95 

can you please adjust the starting point to zoom out to so that you can see basically the entire east coast?

then I'll zoom into nashville manually as I speak during the conference presentation.

thx!

**Comment by ozanj** [comment]
map looks fabulous @cyouh95. thank you!
