### ISSUE TITLE
create a background where the images convey networks

### ISSUE THREAD

**Issue by ozanj** [cyouh95/recruiting-chapter#13]
Hey Crystal,

can you experiment w/ a few backgrounds that convey network-y imagery?

https://www.google.com/search?q=vector+network+background+presentation&oq=vector+network+background+presentation&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigAdIBCDUwNTBqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

**Comment by cyouh95** [comment]
I added a couple background options that can be toggled in the [title slide](https://cyouh95.github.io/recruiting-chapter/#/title-slide) (source: [BG1](https://www.freepik.com/premium-vector/abstract-plexus-background-with-connected-lines-dots-plexus-geometric-effect-big-data-complex-with-compounds-lines-plexus-minimal-array-digital-data-visualization-vector-illustration_18145805.htm), [BG2](https://www.freepik.com/free-vector/abstract-low-poly-geometric-dots-lines-data-science-vector_61112955.htm#page=3&query=abstract%20network&position=1&from_view=keyword&track=ais&uuid=3917f3b8-6ea7-43a6-923a-561a8211fedf)) - hopefully these look okay?

I had to blur the background a little on the text slides so it wouldn't be too distracting. I couldn't find too many good ones that were simple / more around the borders.

**Comment by ozanj** [comment]
these are fabulous.

and we can leave the bg1 and bg2 in title slide. like the ability to change on the fly!
