### ISSUE TITLE
private high schools that received a visit but were not in 2017-18 PSS

### ISSUE THREAD

**Issue by ozanj** [cyouh95/recruiting-chapter#2]
[from igraph_recruiting.R script]

        # 278 private high schools that received at least one visit were not in the 2017-18 PSS data
        # below, I merge these 278 obs to high-school-level data from events.csv [all obs merge] and to high-school-level data from hs_data.csv [all obs merge]
        # One of you take the lead in investigating these 278 obs
          # confirm that these schools were in previous iteration of PSS      
          # we need to figure out why they were not in the 2017-18 PSS data
            # did the school close?
        # after investigating, need to decide what to do about these 278 schools
          # e.g., should we use non-missing data from previous iteration of PSS?

FYI - @irmacastaneda0822 : I took your code about 2017-18 PSS data from data_cleaning.R and pasted it all into new file pss_data_cleaning.R

- nice job on the code Irma!

**Comment by cyouh95** [comment]
https://docs.google.com/spreadsheets/d/1A4nMT3Ru2rOgs3NIN4jS6d8LtevjoIY1yrtxWbQS1hQ/edit#gid=673325162

I checked ~20 schools from various states and so far, none of the schools are closed and I can't find them in the 2017-18 search [here](https://nces.ed.gov/globallocator/) even if I search by name (ie. confirm the school didn't switch ID or anything)

One thing most (but not all) of the schools have in common is they are independent (highlighted in the spreadsheet). I remember when we did data checks back then, we did sometimes notice that an independent school sometimes has an NCES ID associated w/ it. Maybe they sometimes report to NCES, but are not required to?

In this case, would we want to stick w/ using the available older PSS data for all schools? Or do we need to check the rest of the schools in the sample as well, if there's some reason we'd want to drop a school?
