### ISSUE TITLE
Create new 4-category measure of religious affiliation

### ISSUE THREAD

**Issue by ozanj** [cyouh95/recruiting-chapter#8]
cc: @cyouh95 @irmacastaneda0822 

I'm dissatisfied w/ our current 4-category measure of religious affiliation. below is an email I sent to a couple sociologists who might have helpful advice:

Dear Mitchell and Amy,

I’m muddling through a network analysis of off-campus recruiting visits to private high schools. We are analyzing visits made by about 13 selective private liberal arts colleges, 13 selective private national universities, and 15 or so public research universities. [my co-author Crystal Han is copied]

Religious affiliation is one of the variables of interest [though not the sole focus of the analysis]. I’m not happy w/ the current measure we are using, but I am ignorant about religious affiliation. So I’d like your general take or a helpful reference.

For practical reasons (table and figure layout), we want to create four-category religious affiliation variable, one that I could apply to both private high schools and to colleges/universities in our sample. Some of the religiously affiliated colleges in our sample include: Sewanee, Notre Dame, Villanova, Boston College, Southern Methodist University, Baylor University, Texas Christian University

Currently, we are using a measure motivated by Murnane and Reardon (2018) [attached], with these categories: nonsectarian, Catholic, conservative Christian, and other religion.

A footnote of Murnane & Reardon defines “conservative Christian” as follows:

- “The U.S. Department of Education classifies conservative Christian schools as those that have membership in at least one of four associations: Accelerated Christian Education, American Association of Christian Schools, Association of Christian Schools International, or Oral Roberts University Education Fellowship (Kena et al., 2016).”
- Kena, G., Hussar, W., McFarland, J., de Brey, C., Musu-Gillette, L., Wang, X., & Dunlop Velez, E. (2016). The condition of education 2016 (No. NCES 2016-144). Washington, DC: U.S. Department of Education, National Center for Education Statistics.”

My basic concerns of the Murnane/Reardon measure are: (A) I don’t love the “conservative Christian” category in general; related, (B) the definition of conservative christian category seems to restrictive. It seems like a lot of private high schools broadly associated with Christianity are being categorized as “other religion.” And (C), seems like the colleges/universities in my sample don’t map very well to the Murnane/reardon 4-category measure.

Ideally, I would like to create a measure with these four categories [I’ll think of snappier category names later]: 

- Nonsectarian
- Catholic
- Non-Catholic Christian
- Other religion

Seems like I could create these measures from the data we have (NCES Private School Survey) and it would be easy to allocate colleges/universities in our sample to this measure.

What I am unsure about (because of my ignorance of religion and religiously affiliated schools), is whether lumping “non-catholic Christian” is a bad idea in the sense that religious affiliation of these schools are so different from one another that they should not be in the same category. If so, this measure wouldn’t shed light on extent to which Christian affiliated colleges visit Christian affiliated private high schools.

**Comment by cyouh95** [comment]
**EDIT**: Renamed old 4-category measure as `religion_4` and the new one as `religion` (i.e., `catholic`, `christian`, `nonsectarian`, `other`)

---

**Original 4-category measure of religious affiliation** (`religion`):

- `catholic`
- `conservative_christian`
  - For private HS, defined as having membership in either _Accelerated Christian Education_, _American Association of Christian Schools_, _Association of Christian Schools International_, or _Oral Roberts University Education Fellowship_
  - For universities, was just [Baylor University](https://en.wikipedia.org/wiki/Baylor_University) (ie. [Baptist](https://en.wikipedia.org/wiki/Baptist_General_Convention_of_Texas))  
- `nonsectarian`
- `other_religion`

```r
# Check frequency count for sample of universities and visited private HS
attributes_df %>% filter(school_id %in% univ_vec) %>% select(religion) %>% table(useNA = 'ifany')
attributes_df %>% filter(school_id %in% privhs_vec) %>% select(religion) %>% table(useNA = 'ifany')
```

**New 4-category measure of religious affiliation** (`religion_4`):

- `catholic`
- `christian`
  - Includes any Non-Catholic Christian that were previously lumped into `other` (which are most of the other religions)
- `nonsectarian`
- `other`
  - Mainly just Islam and Judaism

```r
# Check frequency count for sample of universities and visited private HS
attributes_df %>% filter(school_id %in% univ_vec) %>% select(religion_4) %>% table(useNA = 'ifany')
attributes_df %>% filter(school_id %in% privhs_vec) %>% select(religion_4) %>% table(useNA = 'ifany')

# Quick comparison of religion and religion_4 for sample of private universities
View(attributes_df %>% filter(school_id %in% privu_vec) %>% select(school_id, school_name, religion, religion_4) %>% left_join(univ_data %>% select(univ_id, religion), by = c('school_id' = 'univ_id'), suffix = c('', '_original')))
```

**Additional 5-category measure of religious affiliation for private HS** (`religion_5`): *

- `catholic`
- `conservative_christian`
  - Based on membership in the 4 associations
- `other_christian`
- `nonsectarian`
- `other_religion`

```r
# Check frequency count for sample of visited private HS
privhs_data %>% filter(ncessch %in% privhs_vec) %>% select(religion_5) %>% table(useNA = 'ifany')
```

_* This is currently not added as a vertex attribute_
